name: Electronegativity

on: push

jobs:
  electronegativity:
    name: Electronegativity Electron security check
    runs-on: ubuntu-latest
    steps:
      - name: Electronegativity
        uses: doyensec/electronegativity-action@v1.1